---
kind: pipeline
name: kube-ops-view

steps:
  - name: deploy
    image: mosstech/drone-gke-deployer:latest
    environment:
      GCP_PROJECT_ID: 
        from_secret: MW_GCP_PROJECT
      HOSTNAME:
        from_secret: KOV_HOSTNAME
      USERNAME:
        from_secret: KOV_USERNAME
      PASSWORD:
        from_secret: KOV_PASSWORD
      K8S_DEPLOYER_CREDS:
        from_secret: MW_K8S_DEPLOYER
      K8S_CLUSTER_NAME:
        from_secret: MW_K8S_CLUSTER_NAME
    commands:
      - ./deploy.sh
    when:
      event: push
      branch: master
