stages:
- deploy

deploy:
  stage: deploy
  only:
    - master
  image: mosstech/ci-tools:latest
  before_script:
  - echo "${GOOGLE_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
  - region=$(gcloud container clusters list --project=${GCP_PROJECT_ID} --filter "NAME=${CLUSTER_NAME}" --format "value(zone)")
  - gcloud container clusters get-credentials ${CLUSTER_NAME} --project=${GCP_PROJECT_ID} --region=${region}
  script:
  - kubectl apply -f ./k8s/namespace.yaml
  - kustomize build ./k8s/ | kubectl apply -f -
  - kubectl rollout status deploy/kube-ops-view -n=ops-view
