# nginx.ingress.kubernetes.io/auth-type: basic
# nginx.ingress.kubernetes.io/auth-secret: basic-auth
# nginx.ingress.kubernetes.io/auth-realm: "Authentication Required!"
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: kube-ops-view
spec:
  parentRefs:
  - kind: Gateway
    name: shared-gateway
    namespace: ingress
  hostnames:
  - ops-view.alexos.dev
  rules:
  - backendRefs:
    - name: kube-ops-view
      port: 80
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ops-view-iap
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-client
      clientID: 482562318875-7aq6p0rf7vms5saau0q2u3tm2uvfksdo.apps.googleusercontent.com
  targetRef:
    group: ""
    kind: Service
    name: kube-ops-view
