---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: kube-ops-view
spec:
  parentRefs:
  - kind: Gateway
    name: shared-gateway
    namespace: ingress
  hostnames:
  - ops-view.alexos.dev
  rules:
  - backendRefs:
    - name: kube-ops-view
      port: 80
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ops-view-iap
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-client
      clientID: 316747838102-9gg4qaera4kge36hrl6fn7n198airicu.apps.googleusercontent.com
  targetRef:
    group: ""
    kind: Service
    name: kube-ops-view
