apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ops-view

commonLabels:
  app: kube-ops

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - rbac.yaml
  - redis.yaml
  - service.yaml
