apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ops-view

commonLabels:
  app: kube-ops

secretGenerator:
  - name: basic-auth
    files:
      - auth

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - redis.yaml
  - service.yaml
  - service-account.yaml
