---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      priorityClassName: high-priority
      # NB: this affects all pods on the host where redis starts up
      initContainers:
        - name: init-redis
          image: busybox
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          command:
            [
              "sh",
              "-c",
              "echo never > /host-sys/kernel/mm/transparent_hugepage/enabled",
            ]
      containers:
        - name: redis
          image: redis:5-alpine
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 6379
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            # we need to use the "redis" uid
            runAsUser: 100
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-conf
            items:
              - key: redis-config
                path: redis.conf
        - name: host-sys
          hostPath:
            path: /sys
